// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gorm "github.com/jinzhu/gorm"
import mock "github.com/stretchr/testify/mock"

// IConnection is an autogenerated mock type for the IConnection type
type IConnection struct {
	mock.Mock
}

// CommitTransaction provides a mock function with given fields:
func (_m *IConnection) CommitTransaction() {
	_m.Called()
}

// CreateNew provides a mock function with given fields: obj
func (_m *IConnection) CreateNew(obj interface{}) error {
	ret := _m.Called(obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDB provides a mock function with given fields:
func (_m *IConnection) GetDB() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// RollbackOnException provides a mock function with given fields:
func (_m *IConnection) RollbackOnException() {
	_m.Called()
}

// RollbackTransaction provides a mock function with given fields:
func (_m *IConnection) RollbackTransaction() {
	_m.Called()
}

// SaveChanges provides a mock function with given fields: obj
func (_m *IConnection) SaveChanges(obj interface{}) error {
	ret := _m.Called(obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
