// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ILogger is an autogenerated mock type for the ILogger type
type ILogger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: data, description, args
func (_m *ILogger) Debug(data interface{}, description string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, data, description)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: data, description, args
func (_m *ILogger) Error(data interface{}, description string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, data, description)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Fatal provides a mock function with given fields: data, description, args
func (_m *ILogger) Fatal(data interface{}, description string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, data, description)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: data, description, args
func (_m *ILogger) Info(data interface{}, description string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, data, description)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Panic provides a mock function with given fields: data, description, args
func (_m *ILogger) Panic(data interface{}, description string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, data, description)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Warn provides a mock function with given fields: data, description, args
func (_m *ILogger) Warn(data interface{}, description string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, data, description)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
