// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// IRoutes is an autogenerated mock type for the IRoutes type
type IRoutes struct {
	mock.Mock
}

// Close provides a mock function with given fields: ctx
func (_m *IRoutes) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *IRoutes) Run() {
	_m.Called()
}

// Setup provides a mock function with given fields:
func (_m *IRoutes) Setup() {
	_m.Called()
}
